# Example YAML file for use in LBL

# Set instrument name
INSTRUMENT: ESPRESSO

# Set data directory
DATA_DIR: /scratch3/lbl/data/espresso/

# Set the data type (SCIENCE, FP or LFC)
DATA_TYPE: SCIENCE

# Set science object name
OBJECT_SCIENCE: LHS-1140

# Set template object name
OBJECT_TEMPLATE: LHS-1140

# Set the object Teff (for mask creation)
OBJECT_TEFF: 3600

# Set the science input file string
INPUT_FILE: '*.fits'

# Set blaze file (None for default)
BLAZE_FILE: None

# Set template file (None for default)
TEMPLATE_FILE: demo-Template_LHS-1140.fits

# Set whether to plot any plots
PLOT: True

# Set whether to do the compute ccf plot
PLOT_COMPUTE_CCF: False

# Set whether to do the compute line plot
PLOT_COMPUTE_LINES: False

# set whether to do the compil cumulative plot
PLOT_COMPIL_CUMUL: True

# Define whether to do the compil binned plot
PLOT_COMPIL_BINNED: True

# Define whether to skip done files
SKIP_DONE: False

# Verbosity (default is 2)
#     0=only warnings/errors
#     1=info/warnings/errors,'
#     2=general/info/warning/errors
VERBOSE: 2

# Whether to use tqdm module in loops (only when verbose=2)
USE_TQDM: True