# Example YAML file for use in LBL

# Set instrument name
INSTRUMENT: HARPS

# Set data directory
DATA_DIR: /scratch3/lbl/data/harps/

# Set the data type (SCIENCE, FP or LFC)
DATA_TYPE: SCIENCE

# Set science object name
OBJECT_SCIENCE: PROXIMA

# Set template object name
OBJECT_TEMPLATE: PROXIMA

# Set the object Teff (for mask creation)
OBJECT_TEFF: 3042

# Set the science input file string
INPUT_FILE: '*e2ds*A.fits'

# Set blaze file (None for default)
BLAZE_FILE: HARPS.2014-09-02T21_06_48.529_blaze_A.fits

# Set template file (None for default)
TEMPLATE_FILE: None

# Set whether to plot any plots
PLOT: True

# Set whether to do the compute ccf plot
PLOT_COMPUTE_CCF: False

# Set whether to do the compute line plot
PLOT_COMPUTE_LINES: False

# set whether to do the compil cumulative plot
PLOT_COMPIL_CUMUL: True

# Define whether to do the compil binned plot
PLOT_COMPIL_BINNED: True

# Define whether to skip done files
SKIP_DONE: True

# Verbosity (default is 2)
#     0=only warnings/errors
#     1=info/warnings/errors,'
#     2=general/info/warning/errors
VERBOSE: 2

# Whether to use tqdm module in loops (only when verbose=2)
USE_TQDM: True